language: python

python: 3.5
env:
  - TOXENV=py27
  - TOXENV=py35

install:
  - pip install -U tox

script:
  - tox -v

before_cache:
  - rm -fr $HOME/.cache/pip/log

cache:
  diretories:
    - $HOME/.cache/pip

after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat

notifications:
  email:
    on_sucess: never
    on_failure: always
